### PR TITLE
fix(typescript): keep the Headers shim assignable to globalThis.Headers on TS 5.6+

### PR DESCRIPTION
**Pull request by ammubhave**
## Problem

The fallback class in the generated `Headers.ts` shim is no longer assignable to `typeof globalThis.Headers` on TypeScript 5.6+:

```
error TS2322: Type 'typeof Headers' is not assignable to type '{ new (init?: HeadersInit | undefined): Headers; prototype: Headers; }'.
  The types returned by 'prototype.entries()' are incompatible between these types.
    Type 'IterableIterator<[string, string]>' is missing the following properties from type
    'HeadersIterator<[string, string]>': map, filter, take, drop, and 9 more.
```

3.75.1 (`fix-headers-iterator-type`) switched `entries()`, `keys()`, `values()` and `[Symbol.iterator]()` from `HeadersIterator<T>` to `IterableIterator<T>` so the shim would compile on TypeScript < 5.6, where `HeadersIterator` does not exist. But from 5.6 on, `lib.dom` types those members as `HeadersIterator<T>`, which extends `IteratorObject` and so carries the iterator helpers (`map`, `filter`, `take`, `drop`, …). `IterableIterator<T>` has none of them, so it is too wide to assign — the 3.75.1 fix traded a break on old TypeScript for a break on current TypeScript.

This only surfaces when the generated sources are type-checked, so SDKs generated with `outputSourceFiles` and consumed from source hit it while prebuilt SDKs do not. We hit it consuming four `fern-typescript-node-sdk` SDKs from source in a Next.js app on TypeScript 6.0.3 with `lib: ["dom", "dom.iterable", "esnext"]`.

## Fix

Derive the four return types from the global rather than naming either iterator type directly, falling back to `IterableIterator<T>` when the global does not declare the member:

```ts
type GlobalHeaders = InstanceType<typeof globalThis.Headers>;
type HeadersEntries = GlobalHeaders extends { entries(): infer R } ? R : IterableIterator<[string, string]>;
type HeadersKeys = GlobalHeaders extends { keys(): infer R } ? R : IterableIterator<string>;
type HeadersValues = GlobalHeaders extends { values(): infer R } ? R : IterableIterator<string>;
```

The fallback matters because `entries`, `keys` and `values` are declared only in `lib.dom.iterable` before TypeScript 6 — a consumer on `lib: ["es2020", "dom"]` does not have them, and indexing them unconditionally fails with `TS2339`.

The aliases also have to resolve outside the class body: `typeof globalThis.Headers` referenced from inside it is circular with the assignment being checked and collapses to `never`.

| | TS 5.5.4 | TS 6.0.3 |
|---|---|---|
| `es2020,dom` | clean | clean |
| `es2020,dom,dom.iterable` | clean | clean |

## Changes

- `generators/typescript/utils/core-utilities/src/core/fetcher/Headers.ts` — the template.
- 264 regenerated `seed/ts-sdk/**` snapshots, applied as the identical text transformation the template produces.
- A changelog entry under `generators/typescript/sdk/changes/unreleased/`.

Eight checked-in copies under `packages/**` were left alone — they predate 3.75.1, still say `HeadersIterator<T>`, and are not seed output.

## Verification

Applied to the four SDKs in our monorepo and type-checked the whole consuming Next.js program: the two remaining `TS2322`s go to zero, with no new errors.

### CODE REVIEW

File: generators/typescript/utils/core-utilities/src/core/fetcher/Headers.ts [hunk 1]
```diff
@@ -1,3 +1,8 @@
+type GlobalHeaders = InstanceType<typeof globalThis.Headers>;
+type HeadersEntriesIterator = ReturnType<GlobalHeaders["entries"]>;
+type HeadersKeysIterator = ReturnType<GlobalHeaders["keys"]>;
+type HeadersValuesIterator = ReturnType<GlobalHeaders["values"]>;
+
 let Headers: typeof globalThis.Headers;
 
 if (typeof globalThis.Headers !== "undefined") {
```
[the remark this answers is not in the document]
Comment (ammubhave) [reply generators/typescript/utils/core-utilities/src/core/fetcher/Headers.ts:8]: Good catch, this reproduced. On TypeScript 5.x `entries`, `keys` and `values` are declared only in `lib.dom.iterable`; only TypeScript 6 moved them into `lib.dom`. So on 5.5.4 with `lib: ["es2020", "dom"]` the indexed access failed with `TS2339: Property 'entries' does not exist on type 'Headers'`.

Each alias now falls back to `IterableIterator<T>` when the global does not declare the member. Verified against 5.5.4 and 6.0.3, each with and without `dom.iterable` — all four clean.

**Comment by ammubhave** [comment]
The two red checks look like fork-PR secret access rather than anything in this change. `test-ete` fails with `⚠ You are not logged in to Fern` and `Failed to get path to IR`, so the three failing files need `FERN_TOKEN`, and the `validate > docs` snapshot only differs by the extra warning that notice adds. `benchmark-report` fails posting its PR comment with a 403. Happy to rerun if a maintainer can trigger them with secrets.
